# Generated by Django 6.0.4 on 2026-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
