# Generated by Django 6.0.4 on 2026-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_business_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='cat_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images'),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='city_photo',
            field=models.ImageField(blank=True, null=True, upload_to='city_images'),
        ),
    ]
