# Generated by Django 6.0.4 on 2026-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_businesscategory_cat_photo_businesscategory_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3),
        ),
    ]
