# Generated by Django 6.0.4 on 2026-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_business_latitude_remove_business_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessimage',
            name='featured_img',
            field=models.BooleanField(default=False),
        ),
    ]
