# Generated by Django 6.0.4 on 2026-06-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_businessimage_featured_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses_by_category', to='listings.businesscategory'),
        ),
    ]
